steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/apurvashingne/cloudbuild.git']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: 
      - '-c'
      - >
       ls -al
  entrypoint: bash
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull gcr.io/searce-playground-v1/apurvapche2:latest || exit 0'
  ]
#step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build', 
   '-t', 
   'gcr.io/searce-playground-v1/apurvapche2:latest',
   '-t', 
   'gcr.io/searce-playground-v1/apurvapche2:latest',
   '.'
  ]
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', '.']
  dir: apur/k8s
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=apurv-cluster-1'
#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'apurvapche2', 
   'apurvapche2=gcr.io/searce-playground-v1/apurvapche2:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=apurv-cluster-1'
