steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/apurvashingne/cloudbuild.git']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/searce-playground-v1/webapache:latest','.']
  
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/searce-playground-v1/webapache:latest']
