apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: apurvapche2
  name: apurvapche2
spec:
  replicas: 1
  selector:
    matchLabels:
      run: apurvapche2
  template:
    metadata:
      labels:
        run: apurvapche2
    spec:
      containers:
      - image: gcr.io/searce-playground-v1/apurvapche2:latest
        name: apurvapache2
        ports:
        - containerPort: 80
