apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: httpdd3
  name: httpdd3
spec:
  replicas: 2
  selector:
    matchLabels:
      run: httpdd3
  template:
    metadata:
      labels:
        run: httpdd3
    spec:
      containers:
       - image: gcr.io/searce-playground-v1/webapache
         name: webapache
         ports:
         - containerPort: 80
